[book]
authors = ["Niko Matsakis"]
language = "en"
multilingual = false
src = "src"
title = "wg-async"

[rust]
edition = "2018"

[output.html]
site-url = "/wg-async/"
git-repository-url = "https://github.com/rust-lang/wg-async"
additional-js =["mermaid.min.js", "mermaid-init.js"]
edit-url-template = "https://github.com/rust-lang/wg-async/tree/master/{path}?mode=edit"

[output.html.fold]
enable = true
level = 0
[preprocessor]
[preprocessor.mermaid]
command = "mdbook-mermaid"

[preprocessor.graphviz]
command = "mdbook-graphviz"

[output.html.redirect]
"/vision/shiny_future/alan_learns_async_on_his_own.html" = "/vision/submitted_stories/shiny_future/alan_learns_async_on_his_own.html"
"/vision/shiny_future/alan_switches_runtimes.html" = "/vision/submitted_stories/shiny_future/alan_switches_runtimes.html"
"/vision/shiny_future/alans_trust_in_the_compiler_is_rewarded.html" = "/vision/submitted_stories/shiny_future/alans_trust_in_the_compiler_is_rewarded.html"
"/vision/shiny_future/barbara_appreciates_performance_tools.html" = "/vision/submitted_stories/shiny_future/barbara_appreciates_performance_tools.html"
"/vision/shiny_future/barbara_enjoys_an_async_sandwich.html" = "/vision/submitted_stories/shiny_future/barbara_enjoys_an_async_sandwich.html"
"/vision/shiny_future/barbara_makes_a_wish.html" = "/vision/submitted_stories/shiny_future/barbara_makes_a_wish.html"
"/vision/shiny_future/barbara_wants_async_rw.html" = "/vision/submitted_stories/shiny_future/barbara_wants_async_rw.html"
"/vision/shiny_future/barbara_wants_async_tracing.html" = "/vision/submitted_stories/shiny_future/barbara_wants_async_tracing.html"
"/vision/shiny_future/template.html" = "/vision/submitted_stories/shiny_future/template.html"
"/vision/status_quo/alan_builds_a_cache.html" = "/vision/submitted_stories/status_quo/alan_builds_a_cache.html"
"/vision/status_quo/alan_builds_a_task_scheduler.html" = "/vision/submitted_stories/status_quo/alan_builds_a_task_scheduler.html"
"/vision/status_quo/alan_creates_a_hanging_alarm.html" = "/vision/submitted_stories/status_quo/alan_creates_a_hanging_alarm.html"
"/vision/status_quo/alan_finds_database_drops_hard.html" = "/vision/submitted_stories/status_quo/alan_finds_database_drops_hard.html"
"/vision/status_quo/alan_has_an_event_loop.html" = "/vision/submitted_stories/status_quo/alan_has_an_event_loop.html"
"/vision/status_quo/alan_hates_writing_a_stream.html" = "/vision/submitted_stories/status_quo/alan_hates_writing_a_stream.html"
"/vision/status_quo/alan_iteratively_regresses.html" = "/vision/submitted_stories/status_quo/alan_iteratively_regresses.html"
"/vision/status_quo/alan_lost_the_world.html" = "/vision/submitted_stories/status_quo/alan_lost_the_world.html"
"/vision/status_quo/alan_misses_c_sharp_async.html" = "/vision/submitted_stories/status_quo/alan_misses_c_sharp_async.html"
"/vision/status_quo/alan_needs_async_in_traits.html" = "/vision/submitted_stories/status_quo/alan_needs_async_in_traits.html"
"/vision/status_quo/alan_picks_web_server.html" = "/vision/submitted_stories/status_quo/alan_picks_web_server.html"
"/vision/status_quo/alan_runs_into_stack_trouble.html" = "/vision/submitted_stories/status_quo/alan_runs_into_stack_trouble.html"
"/vision/status_quo/alan_started_trusting_the_rust_compiler_but_then_async.html" = "/vision/submitted_stories/status_quo/alan_started_trusting_the_rust_compiler_but_then_async.html"
"/vision/status_quo/alan_thinks_he_needs_async_locks.html" = "/vision/submitted_stories/status_quo/alan_thinks_he_needs_async_locks.html"
"/vision/status_quo/alan_tries_a_socket_sink.html" = "/vision/submitted_stories/status_quo/alan_tries_a_socket_sink.html"
"/vision/status_quo/alan_tries_processing_some_files.html" = "/vision/submitted_stories/status_quo/alan_tries_processing_some_files.html"
"/vision/status_quo/alan_tries_to_debug_a_hang.html" = "/vision/submitted_stories/status_quo/alan_tries_to_debug_a_hang.html"
"/vision/status_quo/alan_wants_prefetch_iterator.html" = "/vision/submitted_stories/status_quo/alan_wants_prefetch_iterator.html"
"/vision/status_quo/alan_writes_a_web_framework.html" = "/vision/submitted_stories/status_quo/alan_writes_a_web_framework.html"
"/vision/status_quo/aws_engineer.html" = "/vision/submitted_stories/status_quo/aws_engineer.html"
"/vision/status_quo/aws_engineer/borrow_check_errors.html" = "/vision/submitted_stories/status_quo/aws_engineer/borrow_check_errors.html"
"/vision/status_quo/aws_engineer/coming_from_java.html" = "/vision/submitted_stories/status_quo/aws_engineer/coming_from_java.html"
"/vision/status_quo/aws_engineer/debugging_performance_problems.html" = "/vision/submitted_stories/status_quo/aws_engineer/debugging_performance_problems.html"
"/vision/status_quo/aws_engineer/ecosystem.html" = "/vision/submitted_stories/status_quo/aws_engineer/ecosystem.html"
"/vision/status_quo/aws_engineer/encountering_pin.html" = "/vision/submitted_stories/status_quo/aws_engineer/encountering_pin.html"
"/vision/status_quo/aws_engineer/failure_to_parallelize.html" = "/vision/submitted_stories/status_quo/aws_engineer/failure_to_parallelize.html"
"/vision/status_quo/aws_engineer/figuring_out_the_best_option.html" = "/vision/submitted_stories/status_quo/aws_engineer/figuring_out_the_best_option.html"
"/vision/status_quo/aws_engineer/getting_ready_to_deploy.html" = "/vision/submitted_stories/status_quo/aws_engineer/getting_ready_to_deploy.html"
"/vision/status_quo/aws_engineer/getting_started_with_rust.html" = "/vision/submitted_stories/status_quo/aws_engineer/getting_started_with_rust.html"
"/vision/status_quo/aws_engineer/juggling_error_handling.html" = "/vision/submitted_stories/status_quo/aws_engineer/juggling_error_handling.html"
"/vision/status_quo/aws_engineer/missed_waker_leads_to_lost_performance.html" = "/vision/submitted_stories/status_quo/aws_engineer/missed_waker_leads_to_lost_performance.html"
"/vision/status_quo/aws_engineer/solving_a_deadlock.html" = "/vision/submitted_stories/status_quo/aws_engineer/solving_a_deadlock.html"
"/vision/status_quo/aws_engineer/testing_the_service.html" = "/vision/submitted_stories/status_quo/aws_engineer/testing_the_service.html"
"/vision/status_quo/aws_engineer/using_jni.html" = "/vision/submitted_stories/status_quo/aws_engineer/using_jni.html"
"/vision/status_quo/aws_engineer/using_the_debugger.html" = "/vision/submitted_stories/status_quo/aws_engineer/using_the_debugger.html"
"/vision/status_quo/aws_engineer/writing_a_java_based_service.html" = "/vision/submitted_stories/status_quo/aws_engineer/writing_a_java_based_service.html"
"/vision/status_quo/barbara_anguishes_over_http.html" = "/vision/submitted_stories/status_quo/barbara_anguishes_over_http.html"
"/vision/status_quo/barbara_battles_buffered_streams.html" = "/vision/submitted_stories/status_quo/barbara_battles_buffered_streams.html"
"/vision/status_quo/barbara_benchmarks_async_trait.html" = "/vision/submitted_stories/status_quo/barbara_benchmarks_async_trait.html"
"/vision/status_quo/barbara_bridges_sync_and_async.html" = "/vision/submitted_stories/status_quo/barbara_bridges_sync_and_async.html"
"/vision/status_quo/barbara_builds_an_async_executor.html" = "/vision/submitted_stories/status_quo/barbara_builds_an_async_executor.html"
"/vision/status_quo/barbara_carefully_dismisses_embedded_future.html" = "/vision/submitted_stories/status_quo/barbara_carefully_dismisses_embedded_future.html"
"/vision/status_quo/barbara_compares_some_cpp_code.html" = "/vision/submitted_stories/status_quo/barbara_compares_some_cpp_code.html"
"/vision/status_quo/barbara_gets_burned_by_select.html" = "/vision/submitted_stories/status_quo/barbara_gets_burned_by_select.html"
"/vision/status_quo/barbara_makes_their_first_steps_into_async.html" = "/vision/submitted_stories/status_quo/barbara_makes_their_first_steps_into_async.html"
"/vision/status_quo/barbara_needs_async_helpers.html" = "/vision/submitted_stories/status_quo/barbara_needs_async_helpers.html"
"/vision/status_quo/barbara_plays_with_async.html" = "/vision/submitted_stories/status_quo/barbara_plays_with_async.html"
"/vision/status_quo/barbara_polls_a_mutex.html" = "/vision/submitted_stories/status_quo/barbara_polls_a_mutex.html"
"/vision/status_quo/barbara_tries_async_streams.html" = "/vision/submitted_stories/status_quo/barbara_tries_async_streams.html"
"/vision/status_quo/barbara_tries_unix_socket.html" = "/vision/submitted_stories/status_quo/barbara_tries_unix_socket.html"
"/vision/status_quo/barbara_trims_a_stacktrace.html" = "/vision/submitted_stories/status_quo/barbara_trims_a_stacktrace.html"
"/vision/status_quo/barbara_wants_async_insights.html" = "/vision/submitted_stories/status_quo/barbara_wants_async_insights.html"
"/vision/status_quo/barbara_wants_single_threaded_optimizations.html" = "/vision/submitted_stories/status_quo/barbara_wants_single_threaded_optimizations.html"
"/vision/status_quo/barbara_wants_to_use_ghostcell.html" = "/vision/submitted_stories/status_quo/barbara_wants_to_use_ghostcell.html"
"/vision/status_quo/barbara_wishes_for_easy_runtime_switch.html" = "/vision/submitted_stories/status_quo/barbara_wishes_for_easy_runtime_switch.html"
"/vision/status_quo/barbara_writes_a_runtime_agnostic_lib.html" = "/vision/submitted_stories/status_quo/barbara_writes_a_runtime_agnostic_lib.html"
"/vision/status_quo/grace_deploys_her_service.html" = "/vision/submitted_stories/status_quo/grace_deploys_her_service.html"
"/vision/status_quo/grace_tries_new_libraries.html" = "/vision/submitted_stories/status_quo/grace_tries_new_libraries.html"
"/vision/status_quo/grace_waits_for_gdb_next.html" = "/vision/submitted_stories/status_quo/grace_waits_for_gdb_next.html"
"/vision/status_quo/grace_wants_a_zero_copy_api.html" = "/vision/submitted_stories/status_quo/grace_wants_a_zero_copy_api.html"
"/vision/status_quo/grace_wants_to_integrate_c_api.html" = "/vision/submitted_stories/status_quo/grace_wants_to_integrate_c_api.html"
"/vision/status_quo/grace_writes_a_new_fb_service.html" = "/vision/submitted_stories/status_quo/grace_writes_a_new_fb_service.html"
"/vision/status_quo/niklaus_simulates_hydrodynamics.html" = "/vision/submitted_stories/status_quo/niklaus_simulates_hydrodynamics.html"
"/vision/status_quo/niklaus_wants_to_share_knowledge.html" = "/vision/submitted_stories/status_quo/niklaus_wants_to_share_knowledge.html"
"/vision/status_quo/template.html" = "/vision/submitted_stories/status_quo/template.html"
"/vision/tenets.html" = "/vision/how_it_feels.html"
